version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_TCP_PORT: 3332
    ports:
      - "3332:3332"
    volumes:
      - devdojo_data:/var/lib/mysql
#    cap_add:
#      - SYS_NICE # CAP_SYS_NICE

volumes:
  devdojo_data: