server:
  error:
    include-stacktrace: on_param
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3332/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: 'root'
    password: 'root'
  jpa:
    hibernate:
      ddl-auto: update
